// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoqJoNDCebr7zcB7ARUl4FXKmuSvADGc',
    appId: '1:197932938957:web:0f21c51377260272511b84',
    messagingSenderId: '197932938957',
    projectId: 'polls-app-ab081',
    authDomain: 'polls-app-ab081.firebaseapp.com',
    storageBucket: 'polls-app-ab081.appspot.com',
    measurementId: 'G-7DT25RVRNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3SNYxuXVwT4rxndDYTYeLPBcg0W6CMA',
    appId: '1:197932938957:android:0f74b4e075989ae9511b84',
    messagingSenderId: '197932938957',
    projectId: 'polls-app-ab081',
    storageBucket: 'polls-app-ab081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DR8XKlRbolsmrHFFhRU5n1wC_yKNsC0',
    appId: '1:197932938957:ios:2f86bc138110a68c511b84',
    messagingSenderId: '197932938957',
    projectId: 'polls-app-ab081',
    storageBucket: 'polls-app-ab081.appspot.com',
    iosBundleId: 'com.example.pollApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DR8XKlRbolsmrHFFhRU5n1wC_yKNsC0',
    appId: '1:197932938957:ios:f1ad7eec85fb6635511b84',
    messagingSenderId: '197932938957',
    projectId: 'polls-app-ab081',
    storageBucket: 'polls-app-ab081.appspot.com',
    iosBundleId: 'com.example.pollApplication.RunnerTests',
  );
}
